<!doctype html>
<html class="no-js" lang="zxx">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Place favicon.ico in the root directory -->
      <link rel="shortcut icon" href="<?php echo get_template_directory_uri(); ?>/images/favicon.png" type="image/x-icon">
      <!-- All css here -->
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/bootstrap.min.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/all.min.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/animate.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/meanmenu.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/jquery.fancybox.min.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/slick.css">
      <!-- <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/nice-select.css"> -->
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/icomoon.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/flaticon.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/default.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/style.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/style.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/font-awesome.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/responsive.css">
      <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/custom.css">
      <script src="<?php echo get_template_directory_uri(); ?>/js/vendor/jquery-3.6.0.min.js"></script>

      <link href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.css" rel="stylesheet"/>
      <meta name="google-site-verification" content="6DxHJTeqlAPWFz7jeBFSynzwk4FwynauAeJPMM9re1Y" />



<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-L55LXTCNWQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-L55LXTCNWQ');
</script>



<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-157467351-45"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-157467351-45');
</script>

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-59Q2D4T');</script>
<!-- End Google Tag Manager -->



<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-59Q2D4T"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<?php if ( is_home() || is_front_page() ) { ?>
   <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
   <script type="application/ld+json">
   {
     "@context": "http://schema.org",
     "@type": "LocalBusiness",
     "name": "House of Vape",
     "image": "https://houseofvapeshop.com/wp-content/uploads/2022/12/hov-logo.jpg",
     "telephone": "(951) 893-1709",
     "email": "houseofvape1@gmail.com",
     "address": {
       "@type": "PostalAddress",
       "streetAddress": "944 W 6th St, Ste 113,",
       "addressLocality": "Corona",
       "addressRegion": "CA",
       "postalCode": "92882"
     },
     "url": "https://houseofvapeshop.com/"
   }
   </script>

<?php } ?>
      	<?php wp_head(); ?>
   </head>
   <body <?php body_class(); ?>>
      
      <!--[if lte IE 9]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
      <![endif]-->
      <!--  ====== preloader start ======================================  -->
      <div id="loading">
         <div id="loading-center">
            <div id="loading-center-absolute">
               <div class="object" id="object_four"></div>
               <div class="object" id="object_three"></div>
               <div class="object" id="object_two"></div>
               <div class="object" id="object_one"></div>
            </div>
         </div>
      </div>
      <!--  preloader-end -->
      
      <!-- 20-12-22 -->
      <!--  ====== header-area-start=======================================  -->
      <header>
         <div class="top-ribbon">
            <div class="container">   <?php the_field('warning_message', 'option'); ?></div>
         </div>
         <div id="header-sticky" class="header-area header-area1 white-bg">               
            <div class="header header-padding ml-185 mr-185">
               <div class="container-fluid">
                  <div class="header-mega p-relative">
                     <div class="row align-items-center justify-content-lg-between">
                        <div class="col-xl-2  col-lg-2 col-md-3 col-sm-6 col-5 pr-0 d-flex align-items-center">
                           <div class="logo">
                              <a href="<?php bloginfo('url'); ?>" class="d-block" data-toggle="tooltip" data-selector="true" data-placement="bottom" title="">
                              <img src="<?php the_field('header_logo', 'option'); ?>" alt="House Of Vape">
                              </a>
                           </div>
                        </div>
                        <!-- /col -->
                        <div class="col-xl-7 col-lg-8 col-md-1 col-sm-1 col-1 d-none pr-0 pl-0 pl-lg-15 d-flex align-items-center justify-content-center position-static m-center">  
                           <div class="main-menu">
                              <nav id="mobile-menu">
                                 <?php wp_nav_menu( array(
                                  'container' => false,
                                  'menu_class' => 'd-block',
                                 'theme_location' => 'primary' 
                             ) ); ?>
                                 
                              </nav>
                           </div>
                           <!-- /main-menu -->
                        </div>
                        <!-- /col -->
                        <div class="col-xl-3 col-lg-2 col-md-8 col-sm-5 col-6">
                           <div class="header-right d-flex justify-content-end align-items-center">
                               <form action="<?php echo get_permalink( wc_get_page_id( 'shop' ) ); ?>" method="GET">
                                 <div class="header-search header-search-2 position-relative d-none d-xl-block" data-toggle="tooltip" data-selector="true" data-placement="bottom" title="Search">
                                    <input type="text" placeholder="Search" class="border-0 pl-25 theme-color" <?php echo get_search_query(); ?> name="s">
                                    <span class="position-absolute black-color"><span><i class="far fa-search"></i></span></span>
                                 </div>
                                 </form>
                              <ul>
                                 <li class="h-shop position-relative">
                                    <a href="<?php bloginfo('url') ?>/cart/">
                                    <div class="header-shopping-cart position-relative">
                                       <span class="dark-black-color" data-toggle="tooltip" data-selector="true" data-placement="bottom" title="Add to cart"><span><i class="far fa-shopping-cart"></i></span></span>
                                       <span class="s-count position-absolute theme-bg white text-center" id="ctbagage">
                                           <?php 
                                    global $woocommerce;
                                    //echo $woocommerce->cart->cart_contents_count;
                                   echo WC()->cart->get_cart_contents_count();
                                  ?>
                                       </span>
                                    </div>
                                 </a>
                                    <!--<div class="header-shopping-cart-details position-absolute bg-white border-gray pl-30 pr-30 pt-35 pb-60">
                                       <div class="h-shop-cart-contetn over-x-hidden over-y-scroll">
                                          <ul class="d-flex pb-10 border-b-light-gray">
                                             <li class="h-shop-cart-img pl-0">   
                                                <a class="d-block" href="#"><img src="images/product/product10.jpg" alt=""></a>
                                             </li>
                                             <li class="pl-3">
                                                <h6 class="single-product-name pb-1">
                                                   <a href="#">Blossom Porcelain Side Plates</a>
                                                </h6>
                                                <span class="primary-color">1<span>x</span>$320.00</span>
                                             </li>
                                             <li class="s-p-remove px-1 pl-0">
                                                <span>x</span>
                                             </li>
                                          </ul>
                                          <ul class="d-flex pt-20 pb-15 border-b-light-gray">
                                             <li class="h-shop-cart-img pl-0">   
                                                <a class="d-block" href="#"><img src="images/product/product2.jpg" alt=""></a>
                                             </li>
                                             <li class="pl-3">
                                                <h6 class="single-product-name pb-1"><a href="#">Chair living room fiberglass</a></h6>
                                                <span class="primary-color">1<span>x</span>$120.00</span>
                                             </li>
                                             <li class="s-p-remove px-1 pl-0">
                                                <span>x</span>
                                             </li>
                                          </ul>
                                       </div>
                                       <div class="s-sub-t mt-2 mb-15">
                                          <span class="primary-color">Subtotal:</span>
                                          <span class="primary-color float-right"> $440.00</span>
                                       </div>
                                       <div class="d-sm-flex justify-content-between">
                                          <a href="#" class="web-btn d-inline-block text-uppercase primary-color gray-border2 position-relative over-hidden pl-20 pr-20 pt-10 pb-10 mt-10">view cart<span class="pl-1"><i class="fas fa-long-arrow-alt-right"></i></span></a>
                                          <a href="#" class="web-btn d-inline-block text-uppercase theme-bg border-theme02 position-relative over-hidden pl-20 pr-20 pt-10 pb-10 mt-10 white">checkout<span class="pl-1"><i class="fas fa-long-arrow-alt-right"></i></span></a>
                                       </div>
                                    </div>-->
                                    <!-- /header-shopping-cart -->
                                 </li>
                              </ul>
                              <!--<ul class="header-wishlist pl-2 d-none d-md-block">
                                 <li class="position-relative">
                                    <a href="#" data-toggle="tooltip" data-selector="true" data-placement="bottom" title="View wishlist" class="dark-black-color"><span><i class="far fa-heart"></i></span>
                                    </a>
                                 </li>
                              </ul>-->
                              <ul class="header-account d-none d-md-block">
                                 <li class="d-none d-md-inline-block pl-15">
                                    <a href="<?php bloginfo('url'); ?>/my-account/" data-toggle="tooltip" data-selector="true" data-placement="bottom" title="My Account" class="dark-black-color"><span><i class="far fa-user-circle"></i></span>
                                    </a>
                                 </li>
                              </ul>
                              <ul class="mobile-menubar mt-1 info-bar d-flex ml-45">
                                 <li>
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                 </li>
                                 <li>
                                    <span></span>
                                    <span class="active"></span>
                                    <span></span>
                                 </li>
                                 <li>
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                 </li>
                              </ul>
                           </div>
                           <!-- /header-right -->
                        </div>
                        <!-- /col -->
                     </div>
                     <!-- /row -->
                  </div>
               </div>
               <!-- /container -->
            </div>
         </div>
         <!-- /header-bottom -->
      </header>
      <!--  header-area-end  -->
      <!--  ====== header extra info start================================== -->
      <!-- side-mobile-menu start -->
      <div class="side-mobile-menu bg-white pt-20 pb-30 pl-40 pr-40 pb-100">
         <div class="close-icon float-right mt-20">
            <a class="close-menu d-block" href="javascript:void(0);"><span class="icon-clear"></span></a>
         </div>
         <div class="header-search-content position-relative d-block d-xl-none pt-30" method="GET">
            <form action="<?php echo get_permalink( wc_get_page_id( 'shop' ) ); ?>" class="position-relative mt-50">
               <input class="form-control rounded-0 h5-theme-color px-0" type="text" placeholder="Enter Keyword..." <?php echo get_search_query(); ?> name="s">
               <a class="position-absolute primary-color d-block" href="#"><span><i class="far fa-search"></i></span></a>
            </form>
            
         </div>
         <div class="mobile-menu mt-10"></div>
         <div class="menu-login pt-10 d-block d-md-none">
            <ul class="header-login d-flex justify-content-between mobile-border-b ">
               <li><a href="<?php bloginfo('url'); ?>/my-account/">My Account</a></li>
               <li><a href="<?php bloginfo('url'); ?>/my-account/"><span class="icon-users"></span></a></li>
            </ul>
         </div>
         <!-- /header-right -->
         <h5 class=" primary-color mt-40 pb-1 border-primary-b d-inline-block"><?php the_field('mobile_contact', 'option'); ?></h5>
         <ul class="contact-add mt-20">
            <li class="mb-15 primary-color">
               <span class="pr-1"><i class="fas fa-map-marker-alt"></i></span> 
               <?php the_field('address', 'option'); ?>
            </li>
            <li class="mb-20 primary-color">
               <span class="pr-1"><i class="far fa-envelope"></i></span> 
               <?php the_field('email', 'option'); ?>
            </li>
            <li class="mb-15">
               <a class=" primary-color" href="tell:<?php the_field('contact_no', 'option'); ?>"><span class="pr-1"><i class="fas fa-phone"></i></span> <?php the_field('contact_no', 'option'); ?></a>
            </li>
         </ul>
         <?php the_field('social_icon', 'option'); ?>
         <!-- social-link -->
      </div>
      <!-- /side-mobile-menu -->
      <div class="body-overlay"></div>
      <!-- header extra info end  -->
      <!-- end 20-12-22 -->