<?php
/**
 *
 * 
 * @subpackage The Hanna’s Rentals
 * @since Twenty Twenty-One 1.0
 */

?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no, minimal-ui"/>

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900" rel="stylesheet" />
    <link href="<?php echo bloginfo('template_directory');?>/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo bloginfo('template_directory');?>/css/bootstrap.extension.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo bloginfo('template_directory');?>/css/style.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo bloginfo('template_directory');?>/style.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo bloginfo('template_directory');?>/css/swiper.css" rel="stylesheet" type="text/css" />
    <!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.0/css/swiper.min.css" rel="stylesheet" type="text/css" /> -->
    <link href="<?php echo bloginfo('template_directory');?>/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href='https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/ui-lightness/jquery-ui.css' rel='stylesheet'>
    <link rel="shortcut icon" href="<?php echo bloginfo('template_directory');?>/img/favicon.png" />
   <meta name="facebook-domain-verification" content="y0iu48ht290nwlxhpwr86w3t65peb6" />



    <?php wp_head(); ?>
    <meta name="google-site-verification" content="nxlTOWkyRkSMjGe5rjk58oxuA1S755W7TigTFE3e9Ac" />

<!-- Google tag (gtag.js) --> 
<script async src="https://www.googletagmanager.com/gtag/js?id=G-TQS5D9KVB2"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-TQS5D9KVB2'); </script>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-157467351-50"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());   gtag('config', 'UA-157467351-50');</script>
<?php if ( is_home() || is_front_page() ) { ?>
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "LocalBusiness",
  "name": "Hanna’s Rentals",
  "image": "https://hannasrentals.com/wp-content/uploads/2023/01/pic3.jpg",
  "url": "https://hannasrentals.com/"
}
</script>
    <?php } else if(is_page('contact')) { ?>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "LocalBusiness",
  "name": "Contact Us",
  "telephone": "626-241-2894",
  "email": "thehannasrentals@gmail.com",
  "address": {
    "@type": "PostalAddress",
    "addressRegion": "Southern California",
    "addressCountry": "USA"
  }
}
</script>
    <?php } ?>


</head>

<body <?php body_class(); ?>>
	

  <!-- LOADER -->
  <div id="loader-wrapper"></div>


  <!-- HEADER -->
  <header class="type-1">
    <div class="header-wrapper">
        <a id="logo" href="<?php bloginfo('url');?>"><img src="<?php the_field('logo', 'option'); ?>" alt="The Hanna’s Rentals"/></a>
        <div class="hamburger-icon">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
        <div class="follow style-1">
            <a class="entry" href="https://www.instagram.com/thehannasrentals/" target="_blank"><i class="fa fa-instagram"></i></a>
            <a class="entry" href="https://www.facebook.com/profile.php?id=100086818032584&mibextid=LQQJ4d" target="_blank"><i class="fa fa-facebook"></i></a>
            <a class="entry" href="https://www.yelp.com/biz/the-hanna-s-rentals-rancho-cucamonga?uid=Qj-bUrOlOEZFCBDQPVGQhg&utm_campaign=www_business_share_popup&utm_medium=copy_link&utm_source=(direct)" target="_blank"><i class="fa fa-yelp"></i></a>
        </div>
    </div>
    <div class="navigation-wrapper">
        <nav>
            
          <?php
          wp_nav_menu(
            array(
               'theme_location'  => 'primary', 
               'container' => false,
               'menu_class' => 'd-block'           
           )
        );
        ?>
    </nav>
</div>
</header>






